import Head from 'next/head'
import React from "react";
import {useRouter} from "next/router";

export default function Home() {
   const router = useRouter()

   React.useEffect(() => {
      router.push('/home?dest=Mon Petit Coeur')
   }, [router])

   return (
      <div className={"body"}>
         <Head>
            <title>My Love</title>
            <meta name="description" content="Generated by create next app"/>
            <link rel="icon" href={'/favicon.ico'}/>
         </Head>
      </div>
   )
}
